# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d79bab72366a299dd3ba9cee65e8191c07030327e6ab4f13b4e641f4fa89e1e8f98d1772dacd2fece85c66b13abe2d796c48e49220fa4caed1cbe5d69c56c0f7

test:
  secret_key_base: 790a0c74dec135496c764d316a5fe5a7b992901d76096dddb4d8aa91c224b3f2feb2ee4fdf09018a1f004aba11bce6cb0fa61564d3320b97176cf79a6db90073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
